apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    component: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
     component: redis-master
  template:
    metadata:
      labels:
        component: redis-master
        redis-sentinel: "true"
    spec:
#      nodeSelector:
#        dsaas-redis-master: "true"
      containers:
        - name: master
          image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/redis:6.2.14-alpine
          command:
            - redis-server
            - "--save 60 1"
            - "--loglevel warning"
          env:
            - name: MASTER
              value: "true"
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 6379
#          resources:
#            limits:
#              cpu: "0.1"
          volumeMounts:
            - mountPath: /data
              name: redis-data
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-master-pvc	  
        - hostPath:
            path: /etc/localtime
          name: timezone
