apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
#      hostAliases:
#      - ip: "10.250.238.61"
#        hostnames:
#        - "registry.secuiot"
#      - ip: "10.250.238.64"
#        hostnames:
#        - "db.internal.secudiumiot.com"
#      nodeSelector:
#        dsaas-redis: "true"
      containers:
      - name: redis
        image: sumitsfm.azurecr.io/kubernetes/zeroredis:4.0.6
        env:
          - name: TZ
            value: Asia/Seoul
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "2048Mi"
        volumeMounts:
        - mountPath: /redis-master-data
          name: redis-data
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
      volumes:
        - name: redis-data 
          persistentVolumeClaim:
            claimName: redis-data
        - hostPath:
            path: /etc/localtime
          name: timezone
