---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: postgres
  name: postgres-lb
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: pgql
  selector:
    app: postgresql
  type: LoadBalancer
