apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cs
  labels:
    app: elasticsearch-master
spec:
  selector:
    app: elasticsearch-master
  ports:
  - protocol: "TCP"
    port: 9200
    targetPort: 9200
    name: elasticsearch-9200
  - protocol: "TCP"
    port: 9300
    targetPort: 9300
    name: elasticsearch-9300
  type: ClusterIP
