apiVersion: apps/v1 
kind: Deployment
metadata:
  name: elasticsearch-master
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    matchLabels:
      app: elasticsearch-master
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-master
    spec:
      initContainers:
      - name: init-sysctl
        image: docker.io/busybox:1.27.2
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-master
        securityContext:
          privileged: true
        image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/elasticsearch:7.10.0-nori
#        resources:
#          limits:
#            memory: "20Gi"
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: masterport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - name: es-master-config
          mountPath: /etc/elasticsearch/config
        - name: es-master-data
          mountPath: /data
        - name: es-master-logs
          mountPath: /logs
#        - name: timezone
#          mountPath: /etc/localtime
#          readOnly: true
      volumes:
      - name: es-master-config
        persistentVolumeClaim:
          claimName: es-master-config-pvc
      - name: es-master-data
        persistentVolumeClaim:
          claimName: es-master-data-pvc
      - name: es-master-logs
        persistentVolumeClaim:
          claimName: es-master-logs-pvc
#      - name: timezone
#        hostPath:
#          path: /etc/localtime
      nodeSelector:
        dspESType: "master"
