apiVersion: v1
kind: Service
metadata:
  name: spark-master1-svc
  labels:
    name: spark-master1
spec:
  selector:
    name: spark-master1
  ports:
    # the port that this service should serve on
  - name: webui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: spark
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: rest 
    protocol: TCP
    port: 6066
    targetPort: 6066
