apiVersion: v1
kind: Service
metadata:
  name: spark-worker-lb
  labels:
    name: spark-worker
spec:
  selector:
    name: spark-worker
  ports:
    # the port that this service should serve on
  - name: executor-webui
    protocol: TCP
    port: 4040
    targetPort: 4040
  type: LoadBalancer
