apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 3
  serviceName: kafka-svc
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: kafka
          securityContext:
            {}
          image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/kafka:2.2.1_2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9093
              name: server
            - containerPort: 9094
              name: server-2
          command:
          - sh
          - -c
          - "exec /opt/kafka_2.12-2.2.1/bin/kafka-server-start.sh /opt/kafka_2.12-2.2.1/config/server.properties --override broker.id=${HOSTNAME##*-} \
             --override acks=1 \
             --override auto.commit.enable=true \
             --override auto.commit.interval.ms=60000 \
             --override auto.create.topics.enable=true \
             --override auto.leader.rebalance.enable=true \
             --override auto.offset.reset=largest \
             --override background.threads=10 \
             --override buffered.records.per.partition=1000 \
             --override broker.id.generation.enable=true \
             --override compression.type=producer \
             --override connections.max.idle.ms=600000 \
             --override controlled.shutdown.enable=true \
             --override controlled.shutdown.max.retries=3 \
             --override controlled.shutdown.retry.backoff.ms=5000 \
             --override controller.socket.timeout.ms=30000 \
             --override default.replication.factor=1 \
             --override delete.retention.ms=86400000 \
             --override delete.topic.enable=true \
             --override fetch.purgatory.purge.interval.requests=1000 \
             --override group.max.session.timeout.ms=700000 \
             --override group.min.session.timeout.ms=6000 \
             --override inter.broker.protocol.version=2.2-IV1 \
             --override leader.imbalance.check.interval.seconds=300 \
             --override leader.imbalance.per.broker.percentage=10 \
             --override listeners=INTERNAL_PLAINTEXT://:9093,EXTERNAL_PLAINTEXT://:9094 \
             --override log.cleaner.backoff.ms=15000 \
             --override log.cleaner.dedupe.buffer.size=134217728 \
             --override log.cleaner.delete.retention.ms=86400000 \
             --override log.cleaner.enable=true \
             --override log.cleaner.io.buffer.load.factor=0.9 \
             --override log.cleaner.io.buffer.size=524288 \
             --override log.cleaner.io.max.bytes.per.second=1.7976931348623157E308 \
             --override log.cleaner.min.cleanable.ratio=0.5 \
             --override log.cleaner.min.compaction.lag.ms=0 \
             --override log.cleaner.threads=1 \
             --override log.cleanup.policy=delete \
             --override log.dirs=/var/lib/kafka/$POD_NAME \
             --override log.flush.interval.messages=9223372036854775807 \
             --override log.flush.offset.checkpoint.interval.ms=60000 \
             --override log.flush.scheduler.interval.ms=9223372036854775807 \
             --override log.index.interval.bytes=4096 \
             --override log.index.size.max.bytes=10485760 \
             --override log.message.timestamp.difference.max.ms=9223372036854775807 \
             --override log.message.timestamp.type=CreateTime \
             --override log.preallocate=false \
             --override log.retention.bytes=-1 \
             --override log.retention.check.interval.ms=300000 \
             --override log.retention.hours=24 \
             --override log.roll.hours=24 \
             --override log.roll.jitter.hours=0 \
             --override log.segment.bytes=1073741824 \
             --override log.segment.delete.delay.ms=60000 \
             --override max.connections.per.ip=2147483647 \
             --override max.poll.records=2000 \
             --override message.max.bytes=1000012 \
             --override min.insync.replicas=1 \
             --override num.io.threads=8 \
             --override num.network.threads=4 \
             --override num.partitions=3 \
             --override num.recovery.threads.per.data.dir=1 \
             --override num.replica.fetchers=1 \
             --override offset.metadata.max.bytes=4096 \
             --override offsets.commit.required.acks=-1 \
             --override offsets.commit.timeout.ms=5000 \
             --override offsets.load.buffer.size=5242880 \
             --override offsets.retention.check.interval.ms=600000 \
             --override offsets.retention.minutes=1440 \
             --override offsets.topic.compression.codec=0 \
             --override offsets.topic.num.partitions=50 \
             --override offsets.topic.replication.factor=1 \
             --override offsets.topic.segment.bytes=104857600 \
             --override producer.purgatory.purge.interval.requests=1000 \
             --override queued.max.requests=2000 \
             --override quota.consumer.default=9223372036854775807 \
             --override quota.producer.default=9223372036854775807 \
             --override replica.fetch.backoff.ms=1000 \
             --override replica.fetch.max.bytes=1048576 \
             --override replica.fetch.min.bytes=1 \
             --override replica.fetch.response.max.bytes=10485760 \
             --override replica.fetch.wait.max.ms=500 \
             --override replica.high.watermark.checkpoint.interval.ms=5000 \
             --override replica.lag.time.max.ms=10000 \
             --override replica.socket.receive.buffer.bytes=65536 \
             --override replica.socket.timeout.ms=30000 \
             --override request.timeout.ms=40000 \
             --override reserved.broker.max.id=1000 \
             --override socket.receive.buffer.bytes=1024000 \
             --override socket.request.max.bytes=104857600 \
             --override socket.send.buffer.bytes=1024000 \
             --override unclean.leader.election.enable=true \
             --override zookeeper.connect=zk-svc:2181 \
             --override zookeeper.session.timeout.ms=6000 \
             --override zookeeper.set.acl=false \
             --override advertised.listeners=INTERNAL_PLAINTEXT://${HOSTNAME}.kafka-svc.default.svc.cluster.local:9093,EXTERNAL_PLAINTEXT://${MY_HOST_IP}:32400 \
             --override listener.security.protocol.map=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT \
             --override inter.broker.listener.name=INTERNAL_PLAINTEXT "
          env:
            - name: KAFKA_HEAP_OPTS
              value: -Xmx1g -Xms1g
            - name: KAFKA_OPTS
              value: -Dlogging.level=INFO
            - name: MY_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: TZ
              value: Asia/Seoul
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
#          resources:
#            requests:
#              memory: 2Gi
          volumeMounts:
            - mountPath: /var/lib/kafka
              name: kafka-data
              subPathExpr: $(POD_NAME)
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zk
              topologyKey: kubernetes.io/hostname
            weight: 1
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kafka
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 300
