###############################
####### For Streamsets

apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamsets-data-pv
  labels:
    type: streamsets-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-027bd8f71c5d01c5c::fsap-0842ba7598f435308
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: streamsets-data-pv
---
