###############################
####### For Streamsets

apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamsets-data-pv
  labels:
    type: streamsets-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0a2bd38b2b7c36367
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: streamsets-data-pv
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamsets-libs-pv
  labels:
    type: streamsets-libs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-03a026734cbc98e62
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-libs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: streamsets-libs-pv
---


###############################
###### For Kafka

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    type: kafka-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-00aa9e6a1a7165d18
---

# Source: kafka/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      type: kafka-pv
---


#################################
##### For Redis

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-pv
  labels:
    type: redis-master-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-09d5b3f0dad7f13b1
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: redis-master-pv
---

######################################
###### For ElasticSearch master

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-master-config-pv
  labels:
    type: es-master-config-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0d50804d56c47ee47
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-master-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: es-master-config-pv
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-master-data-pv
  labels:
    type: es-master-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0f77c2ac1a4ccc124
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-master-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: es-master-data-pv
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-master-logs-pv
  labels:
    type: es-master-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0dc93e8977b2cf007
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-master-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: es-master-logs-pv
---

######################################
###### For ElasticSearch data1

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data1-config-pv
  labels:
    type: es-data1-config-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0a19e5713ea8380ba
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data1-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: es-data1-config-pv
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-data1-data-pv
  labels:
    type: es-data1-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0515bab14b74f34f2
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data1-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: es-data1-data-pv
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-data1-logs-pv
  labels:
    type: es-data1-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-078d7d6d36395cbaf
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data1-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: es-data1-logs-pv
---


######################################
###### For ElasticSearch data2

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data2-config-pv
  labels:
    type: es-data2-config-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0a49bf43dbc51e1e7
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data2-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: es-data2-config-pv
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-data2-data-pv
  labels:
    type: es-data2-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-03443cd702ba1b379
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data2-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: es-data2-data-pv
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-data2-logs-pv
  labels:
    type: es-data2-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0fcca128eeb895614
---

# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data2-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: es-data2-logs-pv
---


######################################
###### For Kibana

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-config-pv
  labels:
    type: kibana-config-pv
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0f4dd982679ee2f87
---
# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      type: kibana-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-data-pv
  labels:
    type: kibana-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-064873f8e3f827eb1
---
# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: kibana-data-pv
---


######################################
###### For PostgreSQL

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-data-pv
  labels:
    type: postgre-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0f707b0849d087dfe
---
# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: postgre-data-pv
---


######################################
###### For Spark

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data-pv
  labels:
    type: spark-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-02e70fdbcc31b8888
---
# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: spark-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-work-log-pv
  labels:
    type: spark-work-log-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07cac985d0f82c76d::fsap-0a27185a7a0477aa0
---
# Source: redis-master/templates/efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-work-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: spark-work-log-pv
---
